### ISSUE TITLE
Sorting Algorithm are missing in cpp 

### ISSUE THREAD

**Issue by rohan-raut** [MohmedIkram/Hacktoberfest2021#69]
I can contribute and add sorting algorithm in cpp directory. I want to add these algorithm. Please assign this issue to me @MohmedIkram .

**Comment by MohmedIkram** [comment]
Yes you can contribute Rohan

**Comment by rohan-raut** [comment]
I cant see my name in the Assignees, please add me in the assignees so that I can start working @MohmedIkram

**Comment by MohmedIkram** [comment]
I have assigned you Rohan

**Comment by rohan-raut** [comment]
Thnx a lot @MohmedIkram
